# This workflow will install Python dependencies, run tests for a single version of Python (3.9)

name: Python application

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test
        run: |
          python -m unittest discover .
      - name: View Coverage
        run: |
          coverage run --source=data,ai_algorithm,finance_algorithm -m unittest discover -s .
          coverage report -m
